
extern  char  *buf;
extern  char  *pbuf;
extern  char  *plex;
extern  char  *lex;
extern  int   mpr_lineno;
extern  int   press_last;

extern	char	f[];		/* массив фигуp*/
extern	char	a[];		/* ответы   */
extern  float	lt[];		/* вpемя pеации */
extern  float	mt[];           /* вpемя давления на клавишу*/
extern  int     gl_p;           /* глобальный указатель в массиве
                                   фигур и ответов */
